# See https://golangci-lint.run/usage/configuration/
linters-settings:
  dupl:
    threshold: 100
  #goconst:
  #  min-len: 2
  #  min-occurrences: 3
  # TODO: try to enable
  # gocritic:
  #  enabled-tags:
  #    - diagnostic
  #    - experimental
  #    - opinionated
  #    - performance
  #    - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
  goimports:
    local-prefixes: github.com/golangci/golangci-lint

  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - depguard
    - errcheck
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - ineffassign
    - nolintlint
    - staticcheck
    - stylecheck
    - unparam
    - asciicheck
    - staticcheck

  # don't enable:
  # - lll
  # - dogsled
  # - gochecknoinits
  # - gomnd
  # - unused

  # TODO: try to enable
  #- varcheck
  #- gocyclo
  #- bodyclose
  #- misspell
  #- nakedret
  #- unconvert
  # - govet
  # - goconst
  # - gocritic
  # - noctx
  # - whitespace
  # - typecheck
  # - dupl
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - wsl
  # - funlen

run:
  timeout: 5m