name: Node build

on:
  workflow_call:

jobs:
  formatter:
    defaults:
      run:
        working-directory: ts/formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - run: npm i
      - run: npm test
      - run: npm run compile
